"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decouple import config
import sys
import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(os.path.join(BASE_DIR, "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default=get_random_secret_key())
DEBUG = config("DJANGO_DEBUG", cast=bool, default=True)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "celery",
    "django_celery_beat",
    "apps.scrapers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {  # Техническая база для Django/Celery
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_TECH_NAME"),
        "USER": config("DB_TECH_USER"),
        "PASSWORD": config("DB_TECH_PASSWORD"),
        "HOST": config("DB_TECH_HOST"),
        "PORT": config("DB_TECH_PORT"),
    },
    "main_db": {  # основная внешняя база
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_MAIN_NAME"),
        "USER": config("DB_MAIN_USER"),
        "PASSWORD": config("DB_MAIN_PASSWORD"),
        "HOST": config("DB_MAIN_HOST"),
        "PORT": config("DB_MAIN_PORT"),
    },
}

DATABASE_ROUTERS = ["config.router.ScraperRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# MINIO
AWS_ACCESS_KEY_ID = config("MINIO_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = config("MINIO_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = config("MINIO_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = config("MINIO_S3_ENDPOINT_URL")

AWS_S3_REGION_NAME = None  # Дефолтный регион MinIO
AWS_S3_FILE_OVERWRITE = True
AWS_S3_VERIFY = True

# Важно: подпись ссылок.
# Если бакет публичный (как мы сделали), ставим False, чтобы ссылки не протухали.
AWS_QUERYSTRING_AUTH = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# # Настройка генерации URL
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"

# REDIS
REDIS_HOST = config("REDIS_HOST")
REDIS_PORT = config("REDIS_PORT")
REDIS_PASSWORD = config("REDIS_PASSWORD")

# Shared proxy pool for both Vavada Celery workers. The password and the paid
# proxy list live only in .env / the ignored proxy file, never in source code.
VAVADA_PROXY_ENABLED = config("VAVADA_PROXY_ENABLED", cast=bool, default=False)
VAVADA_PROXY_FILE = config("VAVADA_PROXY_FILE", default="")
VAVADA_PROXY_URLS = config("VAVADA_PROXY_URLS", default="")
VAVADA_PROXY_SCHEME = config("VAVADA_PROXY_SCHEME", default="http")
VAVADA_PROXY_PORT = config("VAVADA_PROXY_PORT", default="")
VAVADA_PROXY_USERNAME = config("VAVADA_PROXY_USERNAME", default="")
VAVADA_PROXY_PASSWORD = config("VAVADA_PROXY_PASSWORD", default="")
VAVADA_WD_TRUST_COOKIE = config("VAVADA_WD_TRUST_COOKIE", default="")
VAVADA_WD_APPROVAL_COOKIE = config("VAVADA_WD_APPROVAL_COOKIE", default="")
VAVADA_PROXY_REQUESTS_PER_IP = config(
    "VAVADA_PROXY_REQUESTS_PER_IP", cast=int, default=1
)
VAVADA_PROXY_MIN_INTERVAL_SECONDS = config(
    "VAVADA_PROXY_MIN_INTERVAL_SECONDS", cast=int, default=2
)
VAVADA_PROXY_CYCLE_COOLDOWN_SECONDS = config(
    "VAVADA_PROXY_CYCLE_COOLDOWN_SECONDS", cast=int, default=10
)
VAVADA_PROXY_FAILURE_COOLDOWN_SECONDS = config(
    "VAVADA_PROXY_FAILURE_COOLDOWN_SECONDS", cast=int, default=300
)
VAVADA_PROXY_LEASE_TTL_SECONDS = config(
    "VAVADA_PROXY_LEASE_TTL_SECONDS", cast=int, default=300
)
VAVADA_PROXY_WAIT_TIMEOUT_SECONDS = config(
    "VAVADA_PROXY_WAIT_TIMEOUT_SECONDS", cast=int, default=30
)
VAVADA_TASK_RATE_LIMIT = config("VAVADA_TASK_RATE_LIMIT", default="60/m")
VAVADA_SERIALS_TASK_RATE_LIMIT = config(
    "VAVADA_SERIALS_TASK_RATE_LIMIT", default="60/m"
)

# VEOVEO
VEOVEO_API_TOKEN = config("VEOVEO_API_TOKEN", default="")
VEOVEO_CATALOG_API_URL = config(
    "VEOVEO_CATALOG_API_URL",
    default="https://catalog-sync-api.rstprgapipt.com",
)
VEOVEO_REQUEST_TIMEOUT_SECONDS = config(
    "VEOVEO_REQUEST_TIMEOUT_SECONDS", cast=int, default=60
)

# CACHE
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}",
        "TIMEOUT": 600,
    }
}

from celery.schedules import crontab

# CELERY SETTINGS
CELERY_TIMEZONE = "Asia/Tashkent"
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_BEAT_SCHEDULE = {
    # Kmax: пушим свежий round-robin new_releases из Yangi.tv (UZ → Kmax backend,
    # который может стоять за гео-блоком). Каждые 6 часов — достаточно, TTL кеша ~25ч.
    "refresh-kmax-yangi-cache": {
        "task": "apps.scrapers.tasks.yangitv.refresh_kmax_yangi_cache",
        "schedule": crontab(minute=0, hour="*/6"),
    },
}

# URL брокера и бэкенда
CELERY_BROKER_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1"

# --- НАСТРОЙКИ ОЧЕРЕДЕЙ (для разделения Concurrency) ---
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "apps.scrapers.tasks.vavada.parse_single_iframe": {"queue": "vavada_queue"},
    "apps.scrapers.tasks.vavada.spawn_iframe_parsers": {"queue": "default"},
    "apps.scrapers.tasks.vavada.spawn_pirated_rechecks": {"queue": "default"},
    "apps.scrapers.tasks.vavada_serials.spawn_vavada_serials": {"queue": "default"},
    "apps.scrapers.tasks.vavada_serials.parse_vavada_serial": {"queue": "vavada_serials_queue"},
    "apps.scrapers.tasks.kinopoisk.parse_page_list_task": {"queue": "kp_pages_queue"},
    "apps.scrapers.tasks.kinopoisk.parse_single_film_task": {"queue": "kp_films_queue"},
    "apps.scrapers.tasks.kinopoisk_scheduler.discover_task": {"queue": "kp_pages_queue"},
    "apps.scrapers.tasks.kinopoisk_scheduler.expire_task": {"queue": "default"},
    "apps.scrapers.tasks.kinopoisk_scheduler.refill_task": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.collect_all_ids": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.spawn_yt_connect": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.parse_yt_connect": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.spawn_yt_movie_urls": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.parse_yt_movie_url": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.expire_yt_stuck": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.retry_yt_failed": {"queue": "default"},
    "apps.scrapers.tasks.yangitv.refresh_kmax_yangi_cache": {"queue": "default"},
}

PREMIERE = config("premiere", cast=int, default=40)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# For development only
STATICFILES_DIRS = [BASE_DIR / "static_src"]

MEDIA_ROOT = BASE_DIR / "media"
