# Generated by Django 5.2.9 on 2026-02-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAppContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kino_poisk_id', models.IntegerField(unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('poster', models.CharField(blank=True, max_length=100, null=True)),
                ('trailer_link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_serial', models.BooleanField()),
                ('year_production', models.IntegerField(blank=True, null=True)),
                ('slogan', models.TextField()),
                ('age_restriction', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('kino_poisk_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('additional', models.JSONField()),
                ('seasons', models.JSONField()),
                ('language', models.CharField()),
                ('film_content', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_tracks', models.JSONField(blank=True, null=True)),
                ('have_trailer_player', models.BooleanField(blank=True, null=True)),
                ('last_episode', models.IntegerField(blank=True, null=True)),
                ('last_season', models.IntegerField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('premiere', models.DateField(blank=True, null=True)),
                ('premiere_ru', models.DateField(blank=True, null=True)),
                ('add_content_date', models.DateField(blank=True, null=True)),
                ('poster_link', models.CharField(blank=True, max_length=512, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('player_variables', models.JSONField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_ru', models.TextField(blank=True, null=True)),
                ('short_description_uz', models.TextField(blank=True, null=True)),
                ('film_content_uz', models.JSONField(blank=True, null=True)),
                ('id_uz', models.IntegerField(blank=True, null=True, unique=True)),
                ('kmax_rating', models.FloatField()),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('is_parsed_kp', models.CharField(max_length=20)),
                ('is_parsed_ru', models.CharField(max_length=20)),
                ('is_parsed_uz', models.CharField(max_length=20)),
                ('poster_uz', models.CharField(blank=True, max_length=250, null=True)),
                ('last_episode_uz', models.IntegerField(blank=True, null=True)),
                ('last_season_uz', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_app_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YtConnectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(unique=True)),
                ('content_url', models.JSONField(blank=True, default=dict, null=True)),
                ('is_serial', models.BooleanField(default=False)),
                ('parsing_status', models.CharField(choices=[('not_parsed', 'Not parsed'), ('in_progress', 'In Progress'), ('parsed', 'Parsed')], default='not_parsed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
