# Generated by Django 5.2.9 on 2026-05-12 10:57

import apps.stdimage.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('image', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
            ],
            options={
                'db_table': 'content_app_award',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwardYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_app_awardyear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwardYearNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'content_app_awardyearnomination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('poster_1', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_2', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'content_app_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino_poisk_id', models.PositiveIntegerField(unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_uz', models.TextField(blank=True)),
                ('short_description_ru', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('poster', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='content_media/', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('poster_link', models.CharField(blank=True, max_length=512, null=True)),
                ('trailer_link', models.URLField(blank=True, null=True)),
                ('is_serial', models.BooleanField()),
                ('year_production', models.IntegerField(blank=True, null=True)),
                ('slogan', models.TextField(blank=True)),
                ('age_restriction', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('kino_poisk_rating', models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=4, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True)),
                ('kmax_rating', models.FloatField(default=10.0)),
                ('additional', models.JSONField(blank=True, default=dict)),
                ('seasons', models.JSONField(blank=True, default=dict)),
                ('premiere', models.DateField(blank=True, null=True)),
                ('premiere_ru', models.DateField(blank=True, null=True)),
                ('film_content', models.URLField(blank=True, null=True)),
                ('add_content_date', models.DateField(blank=True, null=True)),
                ('audio_tracks', models.JSONField(blank=True, default=list, null=True)),
                ('player_variables', models.JSONField(blank=True, default=list, null=True)),
                ('have_trailer_player', models.BooleanField(default=False, null=True)),
                ('player_id', models.PositiveIntegerField(null=True, unique=True)),
                ('last_season', models.IntegerField(blank=True, null=True)),
                ('last_episode', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('film_content_uz', models.JSONField(blank=True, default=dict, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('id_uz', models.PositiveIntegerField(null=True, unique=True)),
                ('poster_uz', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='content_media_uz/', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('last_season_uz', models.IntegerField(blank=True, null=True)),
                ('last_episode_uz', models.IntegerField(blank=True, null=True)),
                ('add_content_date_uz', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='Русский')),
                ('is_parsed_kp', models.CharField(choices=[('not_parsed', 'Not parsed'), ('in_progress', 'In Progress'), ('parsed', 'Parsed')], default='not_parsed', max_length=20)),
                ('is_parsed_uz', models.CharField(choices=[('not_parsed', 'Not parsed'), ('in_progress', 'In Progress'), ('parsed', 'Parsed')], default='not_parsed', max_length=20)),
                ('is_parsed_ru', models.CharField(choices=[('not_parsed', 'Not parsed'), ('in_progress', 'In Progress'), ('parsed', 'Parsed')], default='not_parsed', max_length=20)),
                ('parsed_at_kp', models.DateTimeField(blank=True, null=True)),
                ('parsed_at_uz', models.DateTimeField(blank=True, null=True)),
                ('parsed_at_ru', models.DateTimeField(blank=True, null=True)),
                ('parse_count_kp', models.PositiveIntegerField(default=0)),
                ('parse_count_uz', models.PositiveIntegerField(default=0)),
                ('parse_count_ru', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'content_app_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=512)),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contentactor',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentComposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contentcomposer',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contentdirector',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contenteditor',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contentoperator',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contentproducer',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentScreenwriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'content_app_contentscreenwriter',
                'ordering': ('ordering',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_app_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_app_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_app_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('img', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('year_of_death', models.IntegerField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, null=True)),
                ('total_movies', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('photo1', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo2', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo3', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo4', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo5', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo6', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo7', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
                ('photo8', apps.stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=250, null=True, upload_to='', variations={'full_size': (1920, -1), 'large': (1366, -1), 'medium': (800, -1), 'small': (400, -1), 'thumbnail': (100, -1)})),
            ],
            options={
                'db_table': 'content_app_participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('films', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'content_app_platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_app_studio',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ContentAppContent',
        ),
        migrations.AddField(
            model_name='ytconnectcontent',
            name='connect_fail_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ytconnectcontent',
            name='parsing_status_player',
            field=models.CharField(choices=[('not_parsed', 'Not parsed'), ('in_progress', 'In Progress'), ('parsed', 'Parsed'), ('failed', 'Failed (too many attempts)')], default='not_parsed', max_length=20),
        ),
        migrations.AddField(
            model_name='ytconnectcontent',
            name='player_fail_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ytconnectcontent',
            name='parsing_status',
            field=models.CharField(choices=[('not_parsed', 'Not parsed'), ('in_progress', 'In Progress'), ('parsed', 'Parsed'), ('failed', 'Failed (too many attempts)')], default='not_parsed', max_length=20),
        ),
        migrations.AddField(
            model_name='ytconnectcontent',
            name='yt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ytconnectcontent',
            name='yt_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
