# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0003_scraperlog_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytconnectcontent",
            name="yt_name_original",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ytconnectcontent",
            name="yt_name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
