# Generated by Codex on 2026-07-18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapers", "0005_content_last_update_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeoVeoContent",
            fields=[
                (
                    "veoveo_id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kinopoisk_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                ("imdb_id", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "is_available",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "video_quality",
                    models.CharField(blank=True, max_length=32),
                ),
                ("audio_tracks_raw", models.TextField(blank=True)),
                (
                    "voice_authors",
                    models.JSONField(blank=True, default=list),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "seasons_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "episodes_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "episodes_by_season",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "episodes_by_voice_authors",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "last_season",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_episode",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "provider_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "parser_veoveo_content",
                "ordering": ("veoveo_id",),
                "indexes": [
                    models.Index(
                        fields=["is_available", "kinopoisk_id"],
                        name="veoveo_avail_kp_idx",
                    ),
                    models.Index(
                        fields=["provider_updated_at"],
                        name="veoveo_provider_upd_idx",
                    ),
                    models.Index(
                        fields=["last_seen_at"],
                        name="veoveo_last_seen_idx",
                    ),
                ],
            },
        ),
    ]
