# Generated by Django 5.2.9 on 2026-07-20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapers", "0005_content_last_update_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeoVeoContent",
            fields=[
                (
                    "veoveo_id",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kinopoisk_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                ("imdb_id", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "is_available",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("player_url", models.TextField(blank=True)),
                (
                    "video_quality",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "age_restriction",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("audio_tracks_raw", models.TextField(blank=True)),
                (
                    "voice_authors",
                    models.JSONField(blank=True, default=list),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "seasons_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "episodes_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "episodes_by_season",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "episodes_by_voice_authors",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "last_season",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_episode",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "provider_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "premiere_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_season_premiere_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "exclusive_start_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "exclusive_end_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "is_lgbt",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "content_app_veoveo_content",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VeoVeoSyncState",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cursor_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "run_token",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "running_since",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                (
                    "last_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_finished_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_from_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_to_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_pages", models.PositiveIntegerField(default=0)),
                ("last_received", models.PositiveIntegerField(default=0)),
                ("last_created", models.PositiveIntegerField(default=0)),
                ("last_updated", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "VeoVeo sync state",
                "verbose_name_plural": "VeoVeo sync states",
            },
        ),
    ]
