# Generated by Codex on 2026-08-03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapers", "0007_veoveocontent_episode_previews"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImdbChartEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_key",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "imdb_id",
                    models.CharField(db_index=True, max_length=16),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "imdb_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "vote_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source_url", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "content_app_imdb_chart_entry",
                "managed": False,
                "indexes": [
                    models.Index(
                        fields=["chart_key", "is_active", "position"],
                        name="scrapers_im_chart__689104_idx",
                    ),
                    models.Index(
                        fields=["chart_key", "fetched_at"],
                        name="scrapers_im_chart__089d53_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chart_key", "imdb_id"),
                        name="uniq_imdb_chart_entry_chart_imdb",
                    )
                ],
            },
        ),
    ]
